In [49]:
# from here http://puzzlor.com/2016-12_GalaxyOnFire.html
import numpy as np
from sklearn import linear_model

In [50]:
inputs = np.array([[25, 2, 6],
                 [350, 0, 8],
                 [38, 4, 5],
                 [28, 2, 8],
                 [45, 2, 7],
                 [80, 2, 8],
                 [60, 4, 6],
                 [50, 3,  5],
                 [65, 2,  7],
                 [30, 2, 6]])
targets = np.array([51975, 168900, 235600, 171900, 150000, 250000, 294900, 100100, 125400, 72500])

In [51]:
inputs

array([[ 25,   2,   6],
       [350,   0,   8],
       [ 38,   4,   5],
       [ 28,   2,   8],
       [ 45,   2,   7],
       [ 80,   2,   8],
       [ 60,   4,   6],
       [ 50,   3,   5],
       [ 65,   2,   7],
       [ 30,   2,   6]])

In [58]:
reg = linear_model.LinearRegression(fit_intercept = False)
reg.fit(inputs,targets)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

In [59]:
reg.coef_

array([   401.34770356,  45416.62437713,   4734.98681125])

In [60]:
(targets - np.dot(inputs,reg.coef_.T))

array([-77301.86221087,  -9451.59073738,  15007.35569979,  31949.12105594,
         7961.1969066 ,  89179.04047061,  60742.71941013, -79892.19236585,
       -24665.75716468, -58783.60072869])

In [61]:
(targets - np.dot(inputs,reg.coef_)).min()

-79892.192365845083